mysite/urls.py
from django.urls import path, include
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}



urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),

]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed


app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, 
         name='post_detail'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
    path('confirm/', views.confirm, name='confirm'),
    path('delete/', views.delete, name='delete'),
    path('search/', views.post_search, name='post_search'),
    path('self/', views.self, name='self'),
    



]

templates/blog/About.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <style>a {text-decoration: none; }</style>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="footer, address, phone, icons" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script>
		$(document).ready(function(){
	  
		  $("button").click(function(){
	  
			if($("button").text() == "☰"){
			  $("button").text("🞬");
			}else{
			  $("button").text("☰");
			}
			
			$("li").toggle("slow");
		  });  
		});
	</script>
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
	<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.css" />
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<link href="{% static 'css/about.css' %}" rel ="stylesheet">
	<link href="{% static 'css/tablet.css' %}" media="screen and (max-width:800px)" rel ="stylesheet">
    <link href="{% static 'css/phone.css' %}" media="screen and (max-width:530px)" rel ="stylesheet">
</head>

<body>
  <header>
    	<div class="container-fluid">
			<div class="row zsx">
				<div class="col-lg-12 animated ">
					<p class="vcenter">
					<h1> Toretto's Blog </h1>
					<h3>Everything Gist-Tech related</h3>
					</p>
				</div>
			</div>
		</div>
  </header>

  <nav>
	<ul class="link2"> 
		<button>🞬</button>
	  <li> 
		<!-- link one -->
		<a class="link2" href="{% url 'blog:home' %}"> Home </a>
	  </li>
	  <li>
		<!-- link two -->
		 <a class="link2" href="{% url 'blog:about' %}"> About </a>
	  </li>
	  <li>
		<!-- link three -->
		<a class="link2" href="{% url 'blog:contact' %}"> Contact </a>
	  </li>
	  
	</ul>
  </nav>

  <div class="about-section">
	<h1 class="headings">ABOUT US </h1>
   <div id="intro">
	<p>Osublog is a Nigerian Blog created in 2021 from scratch through use of codes.</p>
	<p>Osublog is all about the latest news in Osun State University(UNIOSUN).We give you the best current news on our page, We are hear to give you 
	   the right information so get rid of those silly rumours you hear and view our pages for current and real information.</p>
	<p>Osublog is a blog website with its headquarter in Osun, Nigeria, focused on delivering latest captivating headlines just the 
		way you love it We are a modern media house with a different view of news gathering and delivery. We are aware of the fake news trend 
	    in the online media and have taken up the challenge to correct this trend. We are out to rewrite the rules on how news publishing should 
	    be practiced in a digital age.</p>
	<p>The team at Osublog delivers reliable and verified Nigerian, Africa and world headlines in a simple, easy-to-read format; just the way
		news should be delivered, with a dedicated team of editors. All contents on the website are verified and published on the sound judgement
		of our seasoned editors.</p>
	<p> Osublog is of the view that the media can positively or negatively influence people's individual and collective decision making
		processes, with a massive multiplier effect on the society, hence, we have chosen to help build our society through accurate reportage.</p>
	<p> The blog is headed by <b>Oluwadamilare Akinpelu</b>. You can read more <a href="{% url 'blog:self' %}" class="class1">about him here.</a>
   </div>

  </div>

        <footer class="footer-distributed">
            <div class="footer-left">

                <h3>About <span>Toretto</span> </h3>

				<p class="footer-links">
					<a href="{% url 'blog:home' %}">Home</a>
					|
					<a href="{% url 'blog:about' %}">About</a>
					|
					<a href="{% url 'blog:contact' %}">Contact</a>
				</p>
                <p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>
				<p class="footer-company-name">Copyright 2020 &copy; Toretto's Blog | All Rights Reserved</p>
			</div>

			<div class="footer-center">
				<div>
					<i class="fa fa-map-marker"></i>
					  <p><span>No 10, Kajola Street, New Airport, Ibadan.</span></p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>(+234)8118116332</p>
				</div>
				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:akinpeluoluwadamilare79@gmail.com">akinpeluoluwadamilare79@gmail.com</a></p>
				</div>
			</div>
			<div class="footer-right">
				<p class="footer-company-about">
					<span>About the blog</span>
					We offer training and skill building courses across Technology, Design, Management, Entertainment and Music.</p>
				<div class="footer-icons">
					<a href="https://web.facebook.com/profile.php?id=100005202726012"><i class="fa fa-facebook"></i></a>
					<a href="https://twitter.com/T_o_r_e_tto?s=08'"><i class="fa fa-twitter"></i></a>
					<a href="https://www.instagram.com/exicutive_erroor/"><i class="fa fa-instagram"></i></a>
				</div>
			</div>
		</footer>

</body>

</html>

templates/blog/Contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <style>a {text-decoration: none; }</style>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="keywords" content="footer, address, phone, icons" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <script>
		$(document).ready(function(){
	  
		  $(id="navbutton").click(function(){
	  
			if($(id="navbutton").text() == "☰"){
			  $(id="navbutton").text("🞬");
			}else{
			  $(id="navbutton").text("☰");
			}
			
			$("li").toggle("slow");
		  });  
		});
	</script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.css" />
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

  <link href="{% static 'css/contact.css' %}" rel ="stylesheet">
</head>

   <header>
    	<div class="container-fluid">
			<div class="row zsx">
				<div class="col-lg-12 animated ">
					<p class="vcenter">
					<h1> Toretto's Blog </h1>
					<h3>Everything Gist-Tech related</h3>
					</p>
				</div>
			</div>
		</div>
   </header>
   <nav>
    <ul class="link2"> 
        <button id="navbutton">🞬</button>
      <li> 
        <!-- link one -->
        <a class="link2" href="{% url 'blog:home' %}"> Home </a>
      </li>
      <li>
        <!-- link two -->
         <a class="link2" href="{% url 'blog:about' %}"> About </a>
      </li>
      <li>
        <!-- link three -->
        <a class="link2" href="{% url 'blog:contact' %}"> Contact </a>
      </li>
      
    </ul>
  </nav>

<body>

  <div class="container">
    <div class="wrapper animated ">
      <div class="company-info">
        <h3>Contact Info:</h3>
        <ul>
          <li><i class="fa fa-map-marker"></i> No 10, Kajola Street, New Airport, Ibadan.</li>
          <li><i class="fa fa-phone"></i> (+234)8118116332</li>
          <li><i class="fa fa-envelope"></i> akinpeluoluwadamilare79@gmail.com</li>
        </ul>
      </div>
      <div class="contact">
        <h3>Email Us</h3>
        <form>
          <p>
            <label>Name</label>
            <input type="text" name="name">
          </p>
          <p>
            <label>Company</label>
            <input type="text" name="company">
          </p>
          <p>
            <label>Email Address</label>
            <input type="email" name="email">
          </p>
          <p>
            <label>Phone Number</label>
            <input type="text" name="phone">
          </p>
          <p class="full">
            <label>Message</label>
            <textarea name="message" rows="5"></textarea>
          </p>
          <p class="full">
            <button class="submitButton" type="submit" >Submit</button>
          </p>
        </form>
      </div>
    </div>
  </div>

         <footer class="footer-distributed">
             <div class="footer-left">

                <h3>About <span>Toretto</span> </h3>

				<p class="footer-links">
					<a href="{% url 'blog:home' %}">Home</a>
					|
					<a href="{% url 'blog:about' %}">About</a>
					|
					<a href="{% url 'blog:contact' %}">Contact</a>
				</p>
                <p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>
				<p class="footer-company-name">Copyright 2020 &copy; Toretto's Blog | All Rights Reserved</p>
			</div>

			<div class="footer-center">
				<div>
					<i class="fa fa-map-marker"></i>
					  <p><span>No 10, Kajola Street, New Airport, Ibadan.</span></p>
				</div>

				<div>
					<i class="fa fa-phone"></i>
					<p>(+234)8118116332</p>
				</div>
				<div>
					<i class="fa fa-envelope"></i>
					<p><a href="mailto:akinpeluoluwadamilare79@gmail.com">akinpeluoluwadamilare79@gmail.com</a></p>
				</div>
			</div>
			<div class="footer-right">
				<p class="footer-company-about">
					<span>About the blog</span>
					We offer training and skill building courses across Technology, Design, Management, Entertainment and Music.</p>
				<div class="footer-icons">
					<a href="https://web.facebook.com/profile.php?id=100005202726012"><i class="fa fa-facebook"></i></a>
					<a href="https://twitter.com/T_o_r_e_tto?s=08'"><i class="fa fa-twitter"></i></a>
					<a href="https://www.instagram.com/exicutive_erroor/"><i class="fa fa-instagram"></i></a>
				</div>
			</div>
		</footer>


</body>
</html>

templates/blog/post_latestposts.html
<ul>
{% for post in latestposts %}
  <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
  </li>
{% endfor %}
</ul>

templates/blog/post_list.html
{% extends "base.html" %}
{% load blog_tags %}

{% block content %}

    {% if tag %}
      <h9>Posts tagged with "{{ tag.name }}"</h9>
    {% endif %}

     {% for post in posts %}
        <h2><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>

        <p class="tags">
           Tags:
           {% for tag in post.tags.all %}
               <a href="{% url 'blog:post_list_by_tag' tag.slug %}">{{ tag.name }}</a>
               {% if not forloop.last %}, {% endif %}
           {% endfor %}
        </p>

     {% if post.image %}
        <div class="view overlay">
          <img class="img-fluid" src="{{post.image.url}}" alt="Responsive image">
        </div>
     {% endif %}

     {% if post.video %}

        <div class="video-responsive">
          <video width="420" height="315" controls>
          <source src="{{post.video.url}}" type="video/mp4">
          </video>
        </div>

     {% endif %}

        <p class="date">Published {{ post.publish }} by {{ post.author }}</p>
        {{ post.body|markdown|truncatewords_html:30 }}
     {% endfor %}

     {% include "pagination.html" with page=posts %}

{% endblock content %}

templates/blog/post_search.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  </head>

{% block content %}
 <div class="well">
  {% if query %}
    <h1>Posts containing "{{ query }}"</h1>
    <h3>
      {% with results.count as total_results %}
          Found {{ total_results }} result{{ total_results|pluralize }}
      {% endwith %}
    </h3>
    {% for post in results %}
        <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
        {{ post.body|truncatewords:5 }}
    {% empty %}
      <p>There are no results for your query.</p>
    {% endfor %}
    <p><a href="{% url 'blog:post_search' %}">Search again</a></p>
  {% else %}
    <h1>Search for posts</h1>
    <form action="." method="get">
      {{ form | crispy }}
      <input type="submit" class="btn btn-success" value="Search">
    </form>
  {% endif %}
 </div>
{% endblock %}

templates/blog/self.html

{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <style>a {text-decoration: none; }</style>
    <meta charset="UTF-8">
    <meta name="viewort" content="widthdevice-width, initial-scale=1.0">
    <meta name="keywords" content="footer, address, phone, icons" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script>
		$(document).ready(function(){
	  
		  $(id="button").click(function(){
	  
			if($(id="button").text() == "☰"){
			  $(id="button").text("🞬");
			}else{
			  $(id="button").text("☰");
			}
			
			$("li").toggle("slow");
		  });  
		});
	</script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script> 
    <link href="{% static 'css/self.css' %}" rel ="stylesheet">
    <link href="{% static 'css/tablet.css' %}" media="screen and (max-width:800px)" rel ="stylesheet">
    <link href="{% static 'css/phone.css' %}" media="screen and (max-width:530px)" rel ="stylesheet">
    
    
</head>

<header>
    <div class="container-fluid">
        <div class="row zsx">
            <div class="col-lg-12 animated ">
                <p class="vcenter">
                <h1> Toretto's Blog </h1>
                <h3>Everything Gist-Tech related</h3>
                </p>
            </div>
        </div>
    </div>
</header>

<nav>
    <ul class="link2"> 
        <button>🞬</button>
      <li> 
        <!-- link one -->
        <a class="link2" href="{% url 'blog:home' %}"> Home </a>
      </li>
      <li>
        <!-- link two -->
         <a class="link2" href="{% url 'blog:about' %}"> About </a>
      </li>
      <li>
        <!-- link three -->
        <a class="link2" href="{% url 'blog:contact' %}"> Contact </a>
      </li>
      
    </ul>
  </nav>
<body>
  <section id="about">
    <h1 class="headings">About OluwaDamilare Akinpelu 
	                   and OluwaDamilola Emmanuel
                        <p>Nigerian Bloggers</p></h1>
    <div id="pic">
        {% for x in pics %}
        <img src="{{x.image.url}}">
        {% endfor %}  
        
        <div id="intro">
          <p>My name is <b>Oluwadamilare Akinpelu;</b> the brain behind Osublog. I am a young, passionate Nigerian freshman
             Blogger and a programmer with so much passion for making things happen with the use of Technology.</p>
          <p>I am a student of Osun State University (UNIOSUN) with experience of programming. My background in programming inform me
             mindful but competitive appraoach by my mates in the same level.</p>
          <p>I am fueled by the passion for understanding the basics of programming. I consider myself a 'forever student,'
             eager to both build on my academic foundation in Computer Science and stay in tune with the latest digital blogging
             strategies through continued research and reading of pdf books on blogging.
             My hunger for knowledge and determianation to turn information into action has contributed to my most recent success
             on creating this blogging site.</p>
		
	  <p>I, Ekunsanmi Emmanuel OluwaDamilola, I am a student of Osun State University (UNIOSUN), Faculty of Basic and Applied 
	      Sciences, Department of Infrormation and Communication Technoogy.
	      I am an actor and aslo a computer scientist. I really love acting because messages can easily be sent through movies, 
	      comedies and that brings about a change in the world and i am all about changes because i also love to bring changes to
              the world through my skills introducing the world to new ideas.    
        </div>
       
    </div>
  </section>

  <div class="container">
    <div class="col-sm-12">
        <h1>Subscriber to our Newsletter</h1>
    </div>
    <div class="col-sm-12">
        {% if email %}
        <p>{{ email }} has been {{ action }}.</p>
        {% endif %}
    </div>
  {% if form %}
    <div class="col-sm-12">
        <form method="post" novalidate>
            {% csrf_token %}
            {{ form  }}
            <br>
            <button type="submit" class="btn btn-success">Subscribe!</button>
        </form>
    </div>
 {% endif %}
 </div>


  <footer class="footer-distributed">
    <div class="footer-left">

       <h3>About <span>Toretto</span> </h3>

       <p class="footer-links">
           <a href="{% url 'blog:home' %}">Home</a>
           |
           <a href="{% url 'blog:about' %}">About</a>
           |
           <a href="{% url 'blog:contact' %}">Contact</a>
       </p>
       <p><a href="{% url 'blog:post_feed' %}">Subscribe to my RSS feed</a></p>
       <p class="footer-company-name">Copyright 2020 &copy; Toretto's Blog | All Rights Reserved</p>
   </div>

   <div class="footer-center">
       <div>
           <i class="fa fa-map-marker"></i>
             <p><span>No 10, Kajola Street, New Airport, Ibadan.</span></p>
       </div>

       <div>
           <i class="fa fa-phone"></i>
           <p>(+234)8118116332</p>
       </div>
       <div>
           <i class="fa fa-envelope"></i>
           <p><a href="mailto:akinpeluoluwadamilare79@gmail.com">akinpeluoluwadamilare79@gmail.com</a></p>
       </div>
   </div>
   <div class="footer-right">
       <p class="footer-company-about">
           <span>About the blog</span>
           We offer training and skill building courses across Technology, Design, Management, Entertainment and Music.</p>
       <div class="footer-icons">
           <a href="https://web.facebook.com/profile.php?id=100005202726012"><i class="fa fa-facebook"></i></a>
           <a href="https://twitter.com/T_o_r_e_tto?s=08'"><i class="fa fa-twitter"></i></a>
           <a href="https://www.instagram.com/exicutive_erroor/"><i class="fa fa-instagram"></i></a>
       </div>
   </div>
  </footer>

</body>
</html>

templates/blog/test_email.html
<p>Test Email</p>
<p>You are reading my email newsletter, and this is one of those newsletters!</p>